/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.ManufacturerRole;

import business.Enterprise.CDCEnterprise;
import business.Inventory.Batch;
import business.Inventory.Vaccine;
import business.business.Business;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class AddInventoryJPanel extends javax.swing.JPanel implements ActionListener{

    JPanel userProcessContainer;
    private Business business;
    private CDCEnterprise enterprise;
    private Batch batch;
    
    public AddInventoryJPanel(JPanel userProcessContainer,Business business,CDCEnterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.enterprise=enterprise;
        populateCmbVaccine();
    }
    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) VaacineJTable.getModel();
        dtm.setRowCount(0);
        for(Batch b: enterprise.getInventory().getBatchList()){
            Object[] row = new Object[8];
            row[0] = b.getBatchNumber();
            row[1] = b.getVaccine().getCode();
            row[2] = b.getVaccine().getName();
            row[3] = b.getVaccine().getQuantity();
            row[4] = b.getVaccine().getStock();
            row[5] = b.getVaccine().getPrice() * b.getVaccine().getQuantity();
            row[6] = b.getVaccine().getFixedQty();
            dtm.addRow(row);
            
        }
        
    }

    private void populateCmbVaccine(){
        cmbVaccine.removeAllItems();
        for(Vaccine vaccine: enterprise.getVaccineCatalog1().getVaccineList()){
            cmbVaccine.addItem(vaccine);
        }
        
        cmbVaccine.addActionListener(new ActionListener() {

           @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Calling Action Listener ");
                          Vaccine vaccine = (Vaccine) cmbVaccine.getSelectedItem();
        System.out.println("get selected item : " + vaccine);
        if (vaccine != null) {
        txtName.setText(vaccine.getName());
        txtPrice.setText(vaccine.getPrice()+"");
        txtQuantity.setText(vaccine.getQuantity()+"");
        txtStdSize.setText(vaccine.getFixedQty()+"");
         }
    }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        cmbVaccine = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBatch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAddVaccine = new javax.swing.JButton();
        btnAddAnother = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VaacineJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtStdSize = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("     Add Vaccines to the Inventory");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 370, 40));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, 30));

        cmbVaccine.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVaccineActionPerformed(evt);
            }
        });
        add(cmbVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 270, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Vaccine Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, -1));

        txtQuantity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtQuantity.setEnabled(false);
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 270, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Vaccine# ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 110, -1));

        txtBatch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtBatch.setEnabled(false);
        add(txtBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 270, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Batch Number");
        jLabel4.setEnabled(false);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 130, -1));

        btnAddVaccine.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddVaccine.setText("Add Vaccine>>");
        btnAddVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVaccineActionPerformed(evt);
            }
        });
        add(btnAddVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 150, 30));

        btnAddAnother.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddAnother.setText("Add Another>>");
        btnAddAnother.setEnabled(false);
        btnAddAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnotherActionPerformed(evt);
            }
        });
        add(btnAddAnother, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 150, 30));

        VaacineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch Number", "vaccine Code", "Vaccine Name", "Vaccine#", "Stock Status", " Cost#", "Std Batch#"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VaacineJTable);
        if (VaacineJTable.getColumnModel().getColumnCount() > 0) {
            VaacineJTable.getColumnModel().getColumn(0).setResizable(false);
            VaacineJTable.getColumnModel().getColumn(1).setResizable(false);
            VaacineJTable.getColumnModel().getColumn(2).setResizable(false);
            VaacineJTable.getColumnModel().getColumn(3).setResizable(false);
            VaacineJTable.getColumnModel().getColumn(4).setResizable(false);
            VaacineJTable.getColumnModel().getColumn(5).setResizable(false);
            VaacineJTable.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 710, 250));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("  View Created Batches  ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Vaccine");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, -1));

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtName.setEnabled(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 270, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Price Per Vaccine");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 130, -1));

        txtPrice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 270, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Refresh>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 130, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Standard Batch# ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        txtStdSize.setEnabled(false);
        add(txtStdSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 270, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVaccineActionPerformed

        try{
            Vaccine vaccine = (Vaccine) cmbVaccine.getSelectedItem();
            //int quantity = Integer.parseInt(txtQuantity.getText());
            int price = Integer.parseInt(txtPrice.getText());
            //Vaccine dummy=null;
            batch = enterprise.getInventory().addBatch();
            Vaccine v = batch.getVaccine();
            //txtQuantity.setText(vaccine.getQuantity()+"");
            //batch = new Batch();
            
//            for(Vaccine vaccineOriginal: enterprise.getVaccineCatalog1().getVaccineList()){
//                if(vaccineOriginal.getName().equals(vaccine)){
//                    dummy=vaccineOriginal;
//                }
//            }
            
            if(null!=vaccine && price > vaccine.getPrice()){
                String message = "Price cannot exceed the set standard Price of " + String.valueOf(vaccine.getPrice());
                JOptionPane.showMessageDialog(null,message);
                enterprise.getInventory().getBatchList().remove(batch);
                Batch.counter--;
            }else{
                v.setCode(vaccine.getCode());
                v.setName(vaccine.getName());
                v.setQuantity(vaccine.getQuantity());
                v.setStock(vaccine.getStock());
                v.setFixedQty(vaccine.getFixedQty());
                v.setPrice(price);
                v.setDateCreated(time());
                v.setLastUpdated(time());
                txtBatch.setText(batch.getBatchNumber());
                txtQuantity.setEnabled(false);
                cmbVaccine.setEnabled(false);
                btnAddAnother.setEnabled(true);
                btnAddVaccine.setEnabled(false);
                JOptionPane.showMessageDialog(null,"New batch added");
                populateTable();
            }
        }
        catch(NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null,"Please enter Valid values.");
        }
    }//GEN-LAST:event_btnAddVaccineActionPerformed

    private void btnAddAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnotherActionPerformed
        cmbVaccine.setEnabled(true);
        //txtQuantity.setEnabled(true);
        btnAddVaccine.setEnabled(true);
       // txtQuantity.setText(null);
    }//GEN-LAST:event_btnAddAnotherActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVaccineActionPerformed

       
       
    }//GEN-LAST:event_cmbVaccineActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VaacineJTable;
    private javax.swing.JButton btnAddAnother;
    private javax.swing.JButton btnAddVaccine;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cmbVaccine;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStdSize;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
