/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.ManufacturerRole;

import business.Enterprise.CDCEnterprise;
import business.Organization.Organization;
import business.business.Business;
import business.userAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rachita
 */
public class ManufacturerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private Business business;
    private UserAccount userAccount;
    private CDCEnterprise enterprise;
    private Organization organization;
    
    public ManufacturerWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Organization organization,CDCEnterprise enterprise,Business business) {
        initComponents();
        this.userAccount=userAccount;
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.enterprise=enterprise;
        this.organization=organization;
        nameJLabel.setText("Welcome >>" + enterprise.getName() + " to Manufacture Work Area");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameJLabel = new javax.swing.JLabel();
        btnViewInventory = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnApproveRequest = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameJLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 530, 40));

        btnViewInventory.setText("View Inventory");
        btnViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInventoryActionPerformed(evt);
            }
        });
        add(btnViewInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 340, 30));

        btnAdd.setText("Add Vaccines to Inventory");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 340, 30));

        btnApproveRequest.setText("Approve/Reject Distributor Requests");
        btnApproveRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveRequestActionPerformed(evt);
            }
        });
        add(btnApproveRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 340, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddInventoryJPanel panel = new AddInventoryJPanel(userProcessContainer,business,enterprise);
        userProcessContainer.add("AddVaccineJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnViewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInventoryActionPerformed
        ViewInventoryJPanel panel = new ViewInventoryJPanel(userProcessContainer,business,enterprise);
        userProcessContainer.add("ViewInventoryJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewInventoryActionPerformed

    private void btnApproveRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveRequestActionPerformed
        // TODO add your handling code here:
        ProcessRequestsJPanel panel = new ProcessRequestsJPanel(userProcessContainer, userAccount,enterprise,organization);
        userProcessContainer.add("ProcessRequestsJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnApproveRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnApproveRequest;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JLabel nameJLabel;
    // End of variables declaration//GEN-END:variables
}
