/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CDCAdminRole;

import business.Enterprise.Enterprise;
import business.business.Business;
import business.network.Network;
import business.userAccounts.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Rachita
 */
public class CDCAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private Business business;
    private Enterprise enterprise;
    private Network countryNet;
    private UserAccount user;

    public CDCAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount user,Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.enterprise = enterprise;
        this.user= user;
        for (Network network : business.getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getName().equals(enterprise.getName())) {
                    countryNet=network;
                }
            }
        }
        nameJLabel.setText("Welcome " + user.getEmployee().getName() + " to Center of Disease Control >> "+ countryNet);
        
        populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        systemJTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        headingJLabel = new javax.swing.JLabel();
        btnManagePHDs = new javax.swing.JButton();
        btnManageDidtributor = new javax.swing.JButton();
        btnManageAdmin = new javax.swing.JButton();
        btnApproveRequests = new javax.swing.JButton();
        btnManageManufacturers = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        nameJLabel = new javax.swing.JLabel();
        ManageOrgAdmins = new javax.swing.JButton();
        btnVaccineCatalog = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnOrganizations = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        systemJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(systemJTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingJLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headingJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(headingJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 810, 60));

        btnManagePHDs.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManagePHDs.setText("Manage Public Health Departments");
        btnManagePHDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePHDsActionPerformed(evt);
            }
        });
        jPanel2.add(btnManagePHDs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 400, 30));

        btnManageDidtributor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManageDidtributor.setText("Manage National  Distributor Organization");
        btnManageDidtributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDidtributorActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageDidtributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 310, 30));

        btnManageAdmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManageAdmin.setText("Manage Public Health Department Administrator Accounts");
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 400, 30));

        btnApproveRequests.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnApproveRequests.setText("Approve Request from State Health Depatment");
        btnApproveRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveRequestsActionPerformed(evt);
            }
        });
        jPanel2.add(btnApproveRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 400, 30));

        btnManageManufacturers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManageManufacturers.setText("Manage Vaccine Manufacturer Organization");
        btnManageManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageManufacturersActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageManufacturers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 310, 30));

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("Send Request to Recall Batch");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 220, 30));

        nameJLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel2.add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 40));

        ManageOrgAdmins.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ManageOrgAdmins.setText("Manage Organizations and Admin Accounts");
        ManageOrgAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrgAdminsActionPerformed(evt);
            }
        });
        jPanel2.add(ManageOrgAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 310, 30));

        btnVaccineCatalog.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnVaccineCatalog.setText("Manage Vaccine Catalog");
        btnVaccineCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccineCatalogActionPerformed(evt);
            }
        });
        jPanel2.add(btnVaccineCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 220, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Manage States Population");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 220, 30));

        btnOrganizations.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOrganizations.setText("View Organizations");
        btnOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizationsActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrganizations, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 510, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cdc.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 320, 230));

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void populateTree() {
        for (Network network : business.getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getName().equals(enterprise.getName())) {

                    DefaultTreeModel dtm = (DefaultTreeModel) systemJTree.getModel();
                    ArrayList<Network> networkList = network.getNetWorkList();
                    ArrayList<Enterprise> enterpriseList;
                    //ArrayList<Enterprise> stateEnterpriseList;
                    DefaultMutableTreeNode states = new DefaultMutableTreeNode("Center Of Disease Control");
                    DefaultMutableTreeNode root = (DefaultMutableTreeNode) dtm.getRoot();
                    root.insert(states, 0);
                    Network stateNetwork;
                    Network cityNetwork = null;
                 //   Enterprise CDCEnterprise = enterprise;
                    Enterprise phdEnterprise;
//                    DefaultMutableTreeNode countryNode;
                    DefaultMutableTreeNode stateNode = null;
                    DefaultMutableTreeNode cityNode;
                    DefaultMutableTreeNode enterpriseNode;
//                    DefaultMutableTreeNode stateEnterpriseNode;
//                    ArrayList<Network> stateNetworkList;
                    ArrayList<Network> cityNetworkList;

//                    for (int i = 0; i < networkList.size(); i++) {
//                        network = networkList.get(i);
//                        countryNode = new DefaultMutableTreeNode(network.getCountry());
//                        countries.insert(countryNode, i);
//                        System.out.println("countryNode" + countryNode);

//                        stateNetworkList = network.getNetWorkList();
                        for (int l = 0; l < networkList.size(); l++) {
                            stateNetwork = networkList.get(l);
                            stateNode = new DefaultMutableTreeNode(stateNetwork.getState());
                            states.insert(stateNode, l);
                            System.out.println("stateNode" + stateNode);
                            
                            enterpriseList = stateNetwork.getEnterpriseDirectory().getEnterpriseList();
                            for (int j = 0; j < enterpriseList.size(); j++) {
                                phdEnterprise = enterpriseList.get(j);
                                enterpriseNode = new DefaultMutableTreeNode(phdEnterprise.getName());
                                stateNode.insert(enterpriseNode, j);
                                }
                            
                            cityNetworkList = stateNetwork.getNetWorkList();
                            for (int m = 0; m < cityNetworkList.size(); m++) {
                                cityNetwork = cityNetworkList.get(m);
                                cityNode = new DefaultMutableTreeNode(cityNetwork.getCity());
                                stateNode.insert(cityNode, m);

                                
                            }
                        }

                    }
//                }
            }
        }
    }
    private void btnManageManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageManufacturersActionPerformed
      ManageManufacturerJPanel panel = new ManageManufacturerJPanel(userProcessContainer, business,enterprise);
      userProcessContainer.add("ManageManufacturerJPanel", panel);
      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageManufacturersActionPerformed

    private void btnManagePHDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePHDsActionPerformed
      AddPHDJPanel panel = new AddPHDJPanel(userProcessContainer, business, countryNet);
      userProcessContainer.add("AddPHDJPanel", panel);
      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePHDsActionPerformed

    private void btnManageDidtributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDidtributorActionPerformed
        
        ManageDistributorJPanel panel = new ManageDistributorJPanel(userProcessContainer,enterprise,business);
        userProcessContainer.add("ManageDistributorJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDidtributorActionPerformed

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
        ManagePHDAdminJPanel panel = new ManagePHDAdminJPanel(userProcessContainer, business,countryNet);
        userProcessContainer.add("ManagePHDAdminJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAdminActionPerformed

    private void ManageOrgAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrgAdminsActionPerformed
        ManageOrganizationAdminsJPanel panel = new ManageOrganizationAdminsJPanel(userProcessContainer, enterprise,business);
        userProcessContainer.add("ManageOrganizationAdminsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrgAdminsActionPerformed

    private void btnApproveRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveRequestsActionPerformed
        ManagePHDRequestesJPanel panel= new ManagePHDRequestesJPanel(userProcessContainer,user,enterprise,business);
        userProcessContainer.add("ManagePHDRequestesJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnApproveRequestsActionPerformed

    private void btnVaccineCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccineCatalogActionPerformed

        ManageVaccineCatalogJPanel panel = new ManageVaccineCatalogJPanel(userProcessContainer,business,enterprise);
        userProcessContainer.add("AddVaccineCatalogJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnVaccineCatalogActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ManageStatePopulationJPanel panel = new ManageStatePopulationJPanel(userProcessContainer, business, countryNet,enterprise);
        userProcessContainer.add("ManageStatePopulationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizationsActionPerformed

        ViewOrganizationsJPanel panel=new ViewOrganizationsJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ViewOrganizationsJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrganizationsActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        RecallJPanel panel = new RecallJPanel();
        userProcessContainer.add("RecallJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageOrgAdmins;
    private javax.swing.JButton btnApproveRequests;
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnManageDidtributor;
    private javax.swing.JButton btnManageManufacturers;
    private javax.swing.JButton btnManagePHDs;
    private javax.swing.JButton btnOrganizations;
    private javax.swing.JButton btnVaccineCatalog;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTree systemJTree;
    // End of variables declaration//GEN-END:variables
}
