/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.PHDAdminRole;

import business.Enterprise.Enterprise;
import business.Enterprise.EnterpriseDirectory;
import business.network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rachita
 */
public class AddProviderJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    EnterpriseDirectory enterpriseDirectory;
    
    public AddProviderJPanel(JPanel userProcessContainer,Enterprise enterprise,Network stateNet) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.network=stateNet;
        NameJlabel.setText(stateNet + " >> " + enterprise.getName());
        populatecmbCityNetworks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameJlabel = new javax.swing.JLabel();
        txtProviderName = new javax.swing.JTextField();
        btnAddProvider = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cmbCity = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Add Provider for ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 41, -1, 30));

        NameJlabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        add(NameJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 116, 30));
        add(txtProviderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 190, 30));

        btnAddProvider.setText("Add>>");
        btnAddProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProviderActionPerformed(evt);
            }
        });
        add(btnAddProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 90, 30));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 30));

        add(cmbCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, 32));

        jLabel2.setText("Select City Network");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 111, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProviderActionPerformed
        String city = (String) cmbCity.getSelectedItem();
        if(network.getEnterpriseDirectory().getEnterpriseList().isEmpty()){
            JOptionPane.showMessageDialog(null,"No centers found. Cannot create a Provider for this Network");
            return;
        }
        else if(txtProviderName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please give a valid name" );
            return;
        }
        else{
            for(Network c: network.getNetWorkList()){
             for(Enterprise e: c.getEnterpriseDirectory().getEnterpriseList()){
                   if(e.getName().equals(txtProviderName)){
                        JOptionPane.showMessageDialog(null,"Provider already exists.");
                        return;
                    }
                }
            }
            for(Network cityNetwork : network.getNetWorkList()){
                if(cityNetwork.getCity().equals(city)){
                    enterpriseDirectory = cityNetwork.getEnterpriseDirectory();
                    
                        enterpriseDirectory.createAndAddEnterprise(txtProviderName.getText(), Enterprise.EnterpriseType.Provider);
                        JOptionPane.showMessageDialog(null,"Provider Added successfully");
                        txtProviderName.setEnabled(false);
                        btnAddProvider.setEnabled(false);
                        cmbCity.setEnabled(false);
                        return;
                    
                }      
            }
        }
    }//GEN-LAST:event_btnAddProviderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populatecmbCityNetworks(){
        cmbCity.removeAllItems();
        for(Network City: network.getNetWorkList()){
            cmbCity.addItem(City.getCity());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameJlabel;
    private javax.swing.JButton btnAddProvider;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cmbCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtProviderName;
    // End of variables declaration//GEN-END:variables
}
