/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.PHDAdminRole;

import business.Enterprise.CDCEnterprise;
import business.Enterprise.Enterprise;
import business.WorkRequest.ClinicShipmentWorkRequest;
import business.WorkRequest.WorkRequest;
import business.business.Business;
import business.network.Network;
import business.userAccounts.UserAccount;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class ApproveProviderRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Business business;
    private Network network;
    
    public ApproveProviderRequestJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, Business business, Network country) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        this.network=country;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        providerRequestJtable = new javax.swing.JTable();
        btnAssign2 = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        brnRefrsh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Approve Provider Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 380, 30));

        providerRequestJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(providerRequestJtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 700, 260));

        btnAssign2.setText("Assign To Self>>");
        btnAssign2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssign2ActionPerformed(evt);
            }
        });
        add(btnAssign2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 140, 30));

        btnProcess.setText("Process Request>>");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 140, 30));

        brnRefrsh.setText("Refresh>>");
        brnRefrsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRefrshActionPerformed(evt);
            }
        });
        add(brnRefrsh, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 140, 30));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssign2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssign2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = providerRequestJtable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a request.");
        }

     //   ClinicShipmentWorkRequest request = (ClinicShipmentWorkRequest) providerRequestJtable.getValueAt(selectedRow,0);
       WorkRequest request = (WorkRequest) providerRequestJtable.getValueAt(selectedRow,0);
        request.setReceiver(userAccount);
        request.setStatus("inProgress");
        btnProcess.setEnabled(true);
        populateTable();
    }//GEN-LAST:event_btnAssign2ActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed

        int selectedRow = providerRequestJtable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a request.");
            return;
        }
        WorkRequest request = (WorkRequest) providerRequestJtable.getValueAt(selectedRow, 0);
        int ok=JOptionPane.showConfirmDialog(null, "Do you want to approve this request?", "Approve/Reject Provider Request", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(ok==0){
        
        System.out.println("enterprise" + enterprise.getName()+ "network"+ network.getRole() );
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            System.out.println("e::" + e.getName() + "network"+ network.getRole() );
            if (e instanceof CDCEnterprise) {
                userAccount.getWorkQueue().getWorkRequestList().add(request);
                e.getWorkQueue().getWorkRequestList().add(request);
                request.setStatus("Request sent to CDC.");
                request.setResolveDate(time());
                 JOptionPane.showMessageDialog(null, "Request Sent to Center of Disease Control.");
                 populateTable();
                 break;
            }
            if (request == null) {
                JOptionPane.showMessageDialog(null, "No Request exsist.");
            }

        }
        }
        else{
            request.setSender(userAccount);
            request.setStatus("Request Rejected");
        }
       
        
        btnProcess.setEnabled(false);
    }//GEN-LAST:event_btnProcessActionPerformed

    private void brnRefrshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRefrshActionPerformed

        populateTable();
    }//GEN-LAST:event_brnRefrshActionPerformed

     public void populateTable() {

        DefaultTableModel dtm = (DefaultTableModel) providerRequestJtable.getModel();
        dtm.setRowCount(0);
        for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver();
            row[3] = request.getStatus();
            dtm.addRow(row);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRefrsh;
    private javax.swing.JButton btnAssign2;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable providerRequestJtable;
    // End of variables declaration//GEN-END:variables
}
