/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ClinicRole;

import business.Enterprise.Enterprise;
import business.order.OrderItem;
import business.Organization.ClinicOrganization;
import business.Organization.Organization;
import business.WorkRequest.ClinicShipmentWorkRequest;
import business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class ViewOrdersJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private ClinicOrganization clinicOrganization;
    private Enterprise enterprise;

    public ViewOrdersJPanel(JPanel userProcessContainer, ClinicOrganization clinicOrganization, Enterprise enterprise) {
        initComponents();
        this.clinicOrganization = clinicOrganization;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrderJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CreatedTime", "Sender", "OrderItem ID", "VaccineID", "VaccineName", "VAccineQuantity", "Request Status", "reason for Rejection"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrderJTable);
        if (OrderJTable.getColumnModel().getColumnCount() > 0) {
            OrderJTable.getColumnModel().getColumn(1).setResizable(false);
            OrderJTable.getColumnModel().getColumn(2).setResizable(false);
            OrderJTable.getColumnModel().getColumn(3).setResizable(false);
            OrderJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 1570, 370));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("View Placed Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 440, 30));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jButton2.setText("Refresh>> ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) OrderJTable.getModel();
        dtm.setRowCount(0);
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            System.out.println("org " + org.getName());
            System.out.println("clinicOrganization.getName() " + clinicOrganization.getName()); 
            if (org instanceof ClinicOrganization && org.getName().equals(clinicOrganization.getName())) {
                System.out.println("org.getWorkQueue().getWorkRequestList()size()"+ org.getWorkQueue().getWorkRequestList().size());
                for (WorkRequest request : org.getWorkQueue().getWorkRequestList()) {
                    if(request instanceof ClinicShipmentWorkRequest){
                    System.out.println("request.getSender()" + request.getSender());
                    ClinicShipmentWorkRequest shipRequest = (ClinicShipmentWorkRequest) request;
                    for (OrderItem order : shipRequest.getOrderRequest().getOrderitemList()) {
                        Object[] row = new Object[8];
                        row[0] = shipRequest.getResolveDate() == null ? shipRequest.getRequestDate() : shipRequest.getResolveDate();
                        row[1] = shipRequest.getSender();
                        row[2] = shipRequest.getOrderRequest().getOrderID();
                        row[3] = order.getVaccine().getCode();
                        row[4] = order.getVaccine().getName();
                        row[5] = order.getQuantity();
                        row[6] = shipRequest.getStatus();
                        row[7] = shipRequest.getRequest();
                        dtm.addRow(row);
                    }
                    }

                }
            }
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
