/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.ClinicRole;


import business.Enterprise.Enterprise;
import business.order.OrderCatalog;
import business.order.Order;
import business.Organization.ClinicOrganization;
import business.WorkRequest.ClinicShipmentWorkRequest;
import business.WorkRequest.WorkRequest;
import business.network.Network;
import business.userAccounts.UserAccount;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class ViewOrderHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrderHistoryJPanel
     */
    JPanel userProcessContainer;
    private OrderCatalog orderCatalog;
    private ClinicOrganization organization;
    private UserAccount user;
    private Enterprise enterprise;
    private Network cityNet;
//    private Order order;
    
    public ViewOrderHistoryJPanel(JPanel userProcessContainer,ClinicOrganization organization, OrderCatalog masterOrderCatalog, UserAccount user,Enterprise enterprise,Network cityNet) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.orderCatalog = masterOrderCatalog;
        this.organization=organization;
        this.enterprise=enterprise;
        this.user=user;
        this.cityNet=cityNet;
        populateOrderTable();
       
    }

    private void populateOrderTable(){
         DefaultTableModel dtm = (DefaultTableModel) OrderJTable.getModel();
         dtm.setRowCount(0);
        
        for(Order order : orderCatalog.getOrderList()){
            System.out.println("order" + order.getOrderID());
                
           // for(OrderItem orderItem : order.getOrderitemList()){
               // System.out.println(" get prod "+ orderItem.getProduct());
           //  System.out.println(" getrice " + orderItem.getPrice());
            Object row[] = new Object[1];
            row[0] = order;
            dtm.addRow(row);
            }
       // }
    }
    
    private void populateRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) RequestJTable.getModel();
        dtm.setRowCount(0);
//         int seleectedRow = OrderJTable.getSelectedRow();
//            if(seleectedRow<0){
//            JOptionPane.showMessageDialog(null,"Please select an order");
//            return;
//        }
//        Order o = (Order) OrderJTable.getValueAt(seleectedRow, 0);
        System.out.println("enterprise" + enterprise.getName());
        for(WorkRequest request: enterprise.getWorkQueue().getWorkRequestList()){
            ClinicShipmentWorkRequest shipmentRequest = (ClinicShipmentWorkRequest) request;
        if(request != null){
            Object[] row = new Object[5];
         
            row[0] = (shipmentRequest.getOrderRequest().getOrderID()==0 ? null : shipmentRequest.getOrderRequest());
            row[1] = shipmentRequest.getSender();
            row[2] = shipmentRequest.getRequestDate();
            row[3] = shipmentRequest.getReceiver() == null ? "": shipmentRequest.getReceiver();
            row[4] = shipmentRequest.getStatus();
            dtm.addRow(row);
        }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        RequestJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("     Submit OrderRequest To The Provider");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 460, 40));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 80, 30));

        OrderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrderJTable);
        if (OrderJTable.getColumnModel().getColumnCount() > 0) {
            OrderJTable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 990, 80));

        RequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order", "Sender", "RequestTime", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(RequestJTable);
        if (RequestJTable.getColumnModel().getColumnCount() > 0) {
            RequestJTable.getColumnModel().getColumn(0).setResizable(false);
            RequestJTable.getColumnModel().getColumn(1).setResizable(false);
            RequestJTable.getColumnModel().getColumn(2).setResizable(false);
            RequestJTable.getColumnModel().getColumn(3).setResizable(false);
            RequestJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 1430, 340));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText(" Select Order ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText(" View OrderShipment Request ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSubmit.setText("Submit Order Request>>");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 190, 220, 30));

        btnView.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnView.setText("View Requests>>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 360, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        int seleectedRow = OrderJTable.getSelectedRow();
        if(seleectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select an order");
            return;
        }
        Order o = (Order) OrderJTable.getValueAt(seleectedRow, 0);
        
        ClinicShipmentWorkRequest request = new ClinicShipmentWorkRequest();
        
        
        
        for(Enterprise e: cityNet.getEnterpriseDirectory().getEnterpriseList()){
            //put a check
            System.out.println("organization" + organization.getName());
            if (e.getName().equals(enterprise.getName()) && organization!=null) {
             //   if (e instanceof ProviderEnterprise) {
                    user.getWorkQueue().getWorkRequestList().add(request);
                    organization.getWorkQueue().getWorkRequestList().add(request);
                    e.getWorkQueue().getWorkRequestList().add(request);
                    request.setSender(user);
                    request.setOrginalClinic(organization.getName());
                    request.setOrginalprovider(e.getName());
                    request.setStatus("Pending with" + enterprise.getName());
                    request.setOrderRequest(o);
                    request.setRequestDate(time());
                    JOptionPane.showMessageDialog(null, "Order Placed Successfully.");
             //   }

            }
        }
         populateRequestTable();
         
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderJTable;
    private javax.swing.JTable RequestJTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
