/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.ProviderRole;

import business.Address.Address;
import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.Organization.ClinicOrganization;
import business.business.Business;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rachita
 */
public class ManageSatelliteClinicJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private Enterprise enterprise;
    private Business business;
    private Organization organization;
    private ClinicOrganization clinicOrganization;
    //Provider provider;
    
    public ManageSatelliteClinicJPanel(JPanel userProcessContainer, Business business, Enterprise enterprise) {
        initComponents();
        this.business=business;
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAddSite = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("          Manage Satellite Clinics in the Network");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 550, 46));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Name ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 40, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 110, 30));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 250, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Street");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));
        add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 190, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("State ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 190, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Country  ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 190, 30));
        add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 190, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("City");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 30, -1));

        btnAddSite.setText("Add Site>>");
        btnAddSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSiteActionPerformed(evt);
            }
        });
        add(btnAddSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 150, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Zip");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 30, -1));
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSiteActionPerformed
        try{
        String name = txtName.getText();
        String street = txtStreet.getText();
        String city = txtCity.getText();
        String state = txtState.getText();
        String Country = txtCountry.getText();
        String zip = txtZip.getText();
        
        
        for(Organization o: enterprise.getOrganizationDirectory().getOrganizationList()){
                if(o.getType().equals(Organization.Type.Clinic)){
                    if(o.getName().equals(name)){
                        JOptionPane.showMessageDialog(null,"The Clinic already exists.");
                        return;
                    }
                }
        }
        if(name.equals("") || state.equals("")|| city.equals("")||Country.equals("")||zip.equals("") || street.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter valid values.");
            return;
        }
        else{           
                        organization= enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Clinic,name);
                      //  provider = providerOrganization.getProviderDirectory().addProvider();
                        clinicOrganization = (ClinicOrganization) organization;
                        Address address = clinicOrganization.getAddress();
                        address.setCountry(Country);
                        address.setState(state);
                        address.setStreet(street);
                        int Zip = Integer.parseInt(zip);
                        address.setZip(Zip);
                        btnAddSite.setEnabled(false);
                        txtName.setEnabled(false);
                        txtCity.setEnabled(false);
                        txtState.setEnabled(false);
                        txtCountry.setEnabled(false);
                        txtZip.setEnabled(false);
                        txtStreet.setEnabled(false);
                        JOptionPane.showMessageDialog(null,"Clinic added successfully.");
                    
                
            
            

        }
        }
        catch(Exception e){
            System.out.println("e" + e);
            JOptionPane.showMessageDialog(null,"Please enter valid values.");
            enterprise.getOrganizationDirectory().getOrganizationList().remove(organization);
            return;
        }
    }//GEN-LAST:event_btnAddSiteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSite;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
