/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ProviderRole;


import business.Enterprise.ProviderEnterprise;
import business.Inventory.Batch;
import business.Organization.Organization;
import business.WorkRequest.ClinicShipmentWorkRequest;
import business.WorkRequest.ShipmentOrder;
import business.WorkRequest.WorkRequest;
import business.business.Business;
import business.userAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class SendClinicOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendClinicOrdersJPanel
     */
    JPanel userProcessContainer;
    private Business business;
    private ProviderEnterprise enterprise;
    private ShipmentOrder shipRequest;
    ShipmentOrder shipmentreq;
    UserAccount user;
    public SendClinicOrdersJPanel(JPanel userProcessContainer, Business business, ProviderEnterprise enterprise,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        this.user=user;
       // this.shipRequest = shipRequest;

        populateShipmentJTable();
    }

    private void populateShipmentJTable() {
        DefaultTableModel dtm = (DefaultTableModel) shipRequestJTable.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request: enterprise.getWorkQueue().getWorkRequestList()){
            if(request!=null && request instanceof ShipmentOrder){
                shipRequest = (ShipmentOrder)request;
                if(shipRequest.getitemOrderRequest() instanceof ClinicShipmentWorkRequest){
                for(Batch batch: shipRequest.getBatchList()){
                Object[] row = new Object[7];
                row[0] = shipRequest;
                row[1] = batch;
                row[2] = batch.getVaccine().getName();
                row[3] = batch.getVaccine();
                row[4] = batch.getVaccine().getQuantity();
                row[5] = batch.getVaccine().getPrice() * batch.getVaccine().getQuantity();
                row[6] = shipRequest.getStatus();
                dtm.addRow(row);
                }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        shipRequestJTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Send Clinic Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jButton2.setText("Refresh>>  ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, -1, -1));

        btnSend.setText("Send>>");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, -1, -1));

        shipRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ShipmentID", "BatchID", "Vaccine Name", "VaccineID", "Vaccine#", "Cost# Batch", "Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(shipRequestJTable);
        if (shipRequestJTable.getColumnModel().getColumnCount() > 0) {
            shipRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            shipRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            shipRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            shipRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            shipRequestJTable.getColumnModel().getColumn(4).setResizable(false);
            shipRequestJTable.getColumnModel().getColumn(5).setResizable(false);
            shipRequestJTable.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 720, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = shipRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select an order.");
        } else {
            
            ShipmentOrder order = (ShipmentOrder) shipRequestJTable.getValueAt(selectedRow, 0);

            if(order.getitemOrderRequest() instanceof ClinicShipmentWorkRequest){
                ClinicShipmentWorkRequest cwr = (ClinicShipmentWorkRequest) order.getitemOrderRequest();
                for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(org.getName().equals(cwr.getOrginalClinic())){
                        order.setStatus("Request Completed");
                        order.setSender(user);
                        org.getWorkQueue().getWorkRequestList().add(order);
                        user.getWorkQueue().getWorkRequestList().add(order);
                        JOptionPane.showMessageDialog(null,"Order Completed Successfully");
                        break;
                    }
                    JOptionPane.showMessageDialog(null,"Clinic with the name of " + cwr.getOrginalClinic() + "is not found in the network");
                }

            }
                
             
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        populateShipmentJTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable shipRequestJTable;
    // End of variables declaration//GEN-END:variables
}
