/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ProviderRole;

import business.Enterprise.Enterprise;
import business.Enterprise.ProviderEnterprise;
import business.order.OrderItem;
import business.WorkRequest.ProviderWorkRequest;
import business.WorkRequest.WorkRequest;
import business.network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class ViewOrdersJPanel extends javax.swing.JPanel {

     private Enterprise enterprise;
     JPanel userProcessContainer;
     Enterprise stateEnterprise;
     Network state;
     
    public ViewOrdersJPanel(JPanel userProcessContainer,  Enterprise enterprise, Enterprise stateEnterprise,Network state) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.stateEnterprise=stateEnterprise;
        this.state=state;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrderJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CreatedTime", "Sender", "OrderItem ID", "VaccineID", "VaccineName", "VAccineQuantity", "Request Status", "reason for Rejection"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrderJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 1100, 490));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("    View Placed Orders");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 250, 30));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 30));

        jButton2.setText("Refresh>> ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) OrderJTable.getModel();
        dtm.setRowCount(0);
        for(Enterprise phd: state.getEnterpriseDirectory().getEnterpriseList()){
            if (enterprise instanceof ProviderEnterprise && phd.getName().equals(stateEnterprise.getName())) {
                for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
                    if(request instanceof ProviderWorkRequest){
                    ProviderWorkRequest shipRequest = (ProviderWorkRequest) request;
                    for (OrderItem order : shipRequest.getOrderRequest().getOrderitemList()) {
                        Object[] row = new Object[8];
                        row[0] = shipRequest.getResolveDate() == null ? shipRequest.getRequestDate() : shipRequest.getResolveDate();
                        row[1] = shipRequest.getSender();
                        row[2] = shipRequest.getOrderRequest().getOrderID();
                        row[3] = order.getVaccine().getCode();
                        row[4] = order.getVaccine().getName();
                        row[5] = order.getQuantity();
                        row[6] = shipRequest.getStatus();
                        row[7] = shipRequest.getRequest();
                        dtm.addRow(row);
                    }
                    }

                }
            }
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
