/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.systemAdminRole;

import business.Inventory.Disease;
import business.Inventory.DiseaseCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rachita
 */
public class AddDiseaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDisease
     */
    JPanel userProcessContainer;
    private DiseaseCatalog diseaseCatalog;
    private Disease disease;
    
    public AddDiseaseJPanel(JPanel userProcessContainer,DiseaseCatalog diseaseCatalog) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.diseaseCatalog=diseaseCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAddDisease = new javax.swing.JButton();
        txtDescription = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Add Diseases");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 22, 211, 38));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 210, 30));

        jLabel2.setText("Disease Name ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 80, 20));

        jLabel3.setText("Disease ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 70, -1));

        txtCode.setEnabled(false);
        add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 30));

        jLabel5.setText("Description");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 70, 20));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));

        btnAddDisease.setText("Add Vaccine>>");
        btnAddDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiseaseActionPerformed(evt);
            }
        });
        add(btnAddDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 130, 30));
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiseaseActionPerformed
        String name = txtName.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter valid values");
            return;
        }
        else{
            
            if(diseaseCatalog.getDiseaseList().size()>0 ){
                for(Disease d: diseaseCatalog.getDiseaseList()){
                    if(d.getName().equals(name)){
                        JOptionPane.showMessageDialog(null,"This disease already exists in the system");
                        return;
                    }
                }
            }
        }
        disease = diseaseCatalog.createNewDisease();
        txtCode.setText(disease.getID());
        disease.setName(name);
        disease.setDescription(txtDescription.getText());
        JOptionPane.showMessageDialog(null,"Disease Added successfully");
        btnAddDisease.setEnabled(false);
        txtName.setEnabled(false);
        txtDescription.setEnabled(false);
        return;
    }//GEN-LAST:event_btnAddDiseaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDisease;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
