/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.systemAdminRole;

import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.business.Business;
import business.network.Network;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Rachita
 */
public class ManageCDCJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    JPanel userProcessContainer;
    private Business business;
    
    public ManageCDCJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
         populatecmbCountry();
    }
    
    private void populatecmbCountry(){
        cmbCountry.removeAllItems();
        for(Network network: business.getNetworkList()){
            cmbCountry.addItem(network);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EnterpriseJTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCountry = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnAddCDC = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Networks");
        EnterpriseJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(EnterpriseJTree);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 840));

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("          Create Center Of Disease Control");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 510, 48));

        cmbCountry.setForeground(new java.awt.Color(51, 51, 255));
        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Country", " " }));
        jPanel2.add(cmbCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 240, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Select Network");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 110, 20));

        btnAddCDC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddCDC.setText("Add Center>>");
        btnAddCDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCDCActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddCDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 140, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 30));

        btnrefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnrefresh.setText("Refresh>>");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 120, 30));

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCDCActionPerformed
        Network network = (Network) cmbCountry.getSelectedItem();
        if(network==null){
            JOptionPane.showMessageDialog(null,"Please select a network");
            return;
        }
        AddCDCJPanel panel = new AddCDCJPanel(userProcessContainer,business, network);
        userProcessContainer.add("AddCDCJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddCDCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        populateTree();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void populateTree(){
        
        DefaultTreeModel dtm = (DefaultTreeModel) EnterpriseJTree.getModel();
        ArrayList<Network> networkList = business.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;

        DefaultMutableTreeNode countries = new DefaultMutableTreeNode("Countries");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) dtm.getRoot();
        root.insert(countries, 0);

        Network network;
        Network stateNetwork = null;
        Enterprise enterprise;
        DefaultMutableTreeNode countryNode;
        DefaultMutableTreeNode stateNode = null;
        DefaultMutableTreeNode enterpriseNode;
        ArrayList<Network> stateNetworkList;

        for (int i = 0; i < networkList.size(); i++) {
            network = networkList.get(i);
            countryNode = new DefaultMutableTreeNode(network.getCountry());
            countries.insert(countryNode, i);
            System.out.println("countryNode"  + countryNode);
                
            stateNetworkList = network.getNetWorkList();
            for (int l = 0; l < stateNetworkList.size(); l++) {
                stateNetwork = stateNetworkList.get(l);
                stateNode = new DefaultMutableTreeNode(stateNetwork.getState());
                countryNode.insert(stateNode,l);
                            
            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            for (int j = 0; j < enterpriseList.size(); j++) {
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                countryNode.insert(enterpriseNode, j);
                
            
                }
                
            }

        }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree EnterpriseJTree;
    private javax.swing.JButton btnAddCDC;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JComboBox cmbCountry;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
