/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.systemAdminRole;

import business.Inventory.Vaccine;
import business.Inventory.VaccineCatalog;
import business.business.Business;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class ManageVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccineJPanel
     */
    JPanel userProcessContainer;
    private Business business;
    private ArrayList<Vaccine> vaccineList;

    public ManageVaccineJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business= business;
        vaccineList=business.getVaccineCatalog().getVaccineList();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VaccineJTable = new javax.swing.JTable();
        btnVaccine = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("   Manage Vaccines");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 219, 42));

        VaccineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Stock", "CreatedTime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VaccineJTable);
        if (VaccineJTable.getColumnModel().getColumnCount() > 0) {
            VaccineJTable.getColumnModel().getColumn(0).setResizable(false);
            VaccineJTable.getColumnModel().getColumn(1).setResizable(false);
            VaccineJTable.getColumnModel().getColumn(2).setResizable(false);
            VaccineJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 860, 320));

        btnVaccine.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnVaccine.setText("Add Vaccine>>");
        btnVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccineActionPerformed(evt);
            }
        });
        add(btnVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 130, 30));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setText("Update Stock>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 130, 30));

        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh>>");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) VaccineJTable.getModel();
        dtm.setRowCount(0);
        for(Vaccine vaccine:vaccineList){
            Object[] row = new Object[4];
            row[0] = vaccine;
            row[1] = vaccine.getName();
            row[2] = vaccine.getStock();
            row[3] = vaccine.getDateCreated();
            dtm.addRow(row);
        }
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccineActionPerformed
        AddVaccineJPanel panel = new AddVaccineJPanel(userProcessContainer,business.getVaccineCatalog());
        userProcessContainer.add("AddVaccineJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnVaccineActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = VaccineJTable.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a vaccine to update.");
            return;
        }
        else{
        Vaccine vaccine = (Vaccine) VaccineJTable.getValueAt(selectedRow,0);
        UpdateStockJPanel panel = new UpdateStockJPanel(userProcessContainer, vaccine);
        userProcessContainer.add("UpdateStockJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();;
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VaccineJTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVaccine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
