/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.systemAdminRole;

import business.Inventory.Disease;
import business.business.Business;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class ManageDiseaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDiseaseJPanel
     */
    JPanel userProcessContainer;
    private Business business;
    private ArrayList<Disease> diseaseList;
    
    public ManageDiseaseJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        diseaseList=business.getDiseaseCatalog().getDiseaseList();
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DiseaseJTable = new javax.swing.JTable();
        btnAddDisease = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("      Manage Diseases");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 264, 38));

        DiseaseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DiseaseJTable);
        if (DiseaseJTable.getColumnModel().getColumnCount() > 0) {
            DiseaseJTable.getColumnModel().getColumn(0).setResizable(false);
            DiseaseJTable.getColumnModel().getColumn(1).setResizable(false);
            DiseaseJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 750, 320));

        btnAddDisease.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddDisease.setText("Add Disease>>");
        btnAddDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiseaseActionPerformed(evt);
            }
        });
        add(btnAddDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 150, 30));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 30));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setText("Update Disease>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 150, 30));

        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh>>");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) DiseaseJTable.getModel();
        dtm.setRowCount(0);
        for(Disease disease:diseaseList){
            Object[] row = new Object[3];
            row[0] = disease;
            row[1] = disease.getName();
            row[2] = disease.getDescription();
            dtm.addRow(row);
        }
    }
    private void btnAddDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiseaseActionPerformed
        AddDiseaseJPanel panel = new AddDiseaseJPanel(userProcessContainer,business.getDiseaseCatalog());
        userProcessContainer.add("AddDiseaseJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddDiseaseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = DiseaseJTable.getSelectedRow();

        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a disease to update.");
            return;
        }
        else{
            Disease disease = (Disease) DiseaseJTable.getValueAt(selectedRow,0);
            UpdateDiseaseJPanel panel = new UpdateDiseaseJPanel(userProcessContainer, disease);
            userProcessContainer.add("UpdateDiseaseJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();;
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DiseaseJTable;
    private javax.swing.JButton btnAddDisease;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
