/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.systemAdminRole;

import business.Inventory.Disease;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rachita
 */
public class UpdateDiseaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateDiseaseJPanel
     */
     JPanel userProcessContainer;
     private Disease disease;
    public UpdateDiseaseJPanel( JPanel userProcessContainer,Disease disease) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.disease=disease;
        txtName.setText(disease.getName());
        txtDescrption.setText(disease.getDescription());
        txtID.setText(disease.getID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnUpdatedisease = new javax.swing.JButton();
        txtDescrption = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Update StockPile");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 41, 232, 35));

        txtName.setEnabled(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 210, 30));

        jLabel2.setText("Disease Name");
        jLabel2.setEnabled(false);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, 20));

        jLabel3.setText("Disease ID");
        jLabel3.setEnabled(false);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 70, -1));

        txtID.setEnabled(false);
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 30));

        jLabel5.setText("Description");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 70, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));

        btnUpdatedisease.setText("Update Vaccine>>");
        btnUpdatedisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatediseaseActionPerformed(evt);
            }
        });
        add(btnUpdatedisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 130, 30));

        txtDescrption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescrptionActionPerformed(evt);
            }
        });
        add(txtDescrption, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdatediseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatediseaseActionPerformed
        try{
            
            String text=txtDescrption.getText();
            disease.setDescription(text);
            txtDescrption.setEnabled(false);
            JOptionPane.showMessageDialog(null,"Information updated successfully.");
            btnUpdatedisease.setEnabled(false);
            return;

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Info could not be updated");
            return;
        }
    }//GEN-LAST:event_btnUpdatediseaseActionPerformed

    private void txtDescrptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescrptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescrptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdatedisease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDescrption;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
