/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.DistributorRole;

import business.Enterprise.Enterprise;
import business.Inventory.Vaccine;
import business.Organization.ManufacturerOrganization;
import business.Organization.Organization;
import business.WorkRequest.DistributorRequest;
import business.userAccounts.UserAccount;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;



public class SubmitManufRequestJPanel extends javax.swing.JPanel {

JPanel userProcessContainer;
UserAccount userAccount;
Vaccine vaccine;
Enterprise enterprise;
DistributorRequest request;
    
    public SubmitManufRequestJPanel(JPanel userProcessContainer,UserAccount userAccount, Enterprise enterprise,Vaccine vaccine) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.vaccine = vaccine;
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        btnRefresh.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RequestStatusJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("        Submit Request To The Manufacturers");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 550, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("    Click Here to Submit the Request to Increase Inventory");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 390, 32));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 110, 30));

        RequestStatusJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requested Vaccine", "Request Date", "Sender", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RequestStatusJTable);
        if (RequestStatusJTable.getColumnModel().getColumnCount() > 0) {
            RequestStatusJTable.getColumnModel().getColumn(0).setResizable(false);
            RequestStatusJTable.getColumnModel().getColumn(1).setResizable(false);
            RequestStatusJTable.getColumnModel().getColumn(2).setResizable(false);
            RequestStatusJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 930, 190));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 30));

        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh>>  ");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 120, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText(" View Sent Requests to Manufacturers   ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        //        if(request instanceof ClinicShipmentWorkRequest){
            //             ClinicShipmentWorkRequest distributorRequest = new ClinicShipmentWorkRequest();
            //        }
        //        else if(request instanceof ProviderWorkRequest){
            //            ProviderWorkRequest distributorRequest = new ProviderWorkRequest();
            //        }
        //
        
         request = new DistributorRequest();
        
        btnRefresh.setEnabled(true);
        Boolean ManufExists = false;
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof ManufacturerOrganization )
            {   ManufExists =true;
                request.setStatus("Pending with Manufacturer");
                request.setRequestDate(time());
                request.setReceiver(null);
                request.setSender(userAccount);
                request.setVaccine(vaccine);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
                org.getWorkQueue().getWorkRequestList().add(request);
                
                JOptionPane.showMessageDialog(null,"Request for increasing the inventory sent.");
                break;
            }
        }

        if(!ManufExists){
            JOptionPane.showMessageDialog(null,"Please create a Manufacturer.");
        }

        populateRequestTable();
        btnSubmit.setEnabled(false);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void populateRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) RequestStatusJTable.getModel();
        dtm.setRowCount(0);
        
       
        if(request != null){
            Object[] row = new Object[4];
            
            row[2] = request.getVaccine();
            row[0] = request.getRequestDate();
            row[1] = request.getSender();
            //row[3] = request.getReceiver()== null ? "": request.getReceiver();
            row[3] = request.getStatus();
            
          
            dtm.addRow(row);
        }
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RequestStatusJTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
