/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.DistributorRole;

import business.Enterprise.Enterprise;
import business.Organization.DistributorOrganization;
import business.Organization.Organization;
import business.WorkRequest.DistributorRequest;
import business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rachita
 */
public class ViewCompletedRequestsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private DistributorOrganization distOrganization;
    public ViewCompletedRequestsJPanel(JPanel userProcessContainer,Organization organization,Enterprise enterprise) {
        initComponents();
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        this.enterprise=enterprise;
        if(organization instanceof DistributorOrganization)
            distOrganization = (DistributorOrganization) organization;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrderJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CreatedTime", "Sender", "VaccineID", "VaccineName", "Request Status", "Response Date", "Rejected Reason"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrderJTable);
        if (OrderJTable.getColumnModel().getColumnCount() > 0) {
            OrderJTable.getColumnModel().getColumn(0).setResizable(false);
            OrderJTable.getColumnModel().getColumn(1).setResizable(false);
            OrderJTable.getColumnModel().getColumn(2).setResizable(false);
            OrderJTable.getColumnModel().getColumn(3).setResizable(false);
            OrderJTable.getColumnModel().getColumn(4).setResizable(false);
            OrderJTable.getColumnModel().getColumn(5).setResizable(false);
            OrderJTable.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 1050, 330));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("   View Completed Requests");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 300, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Refresh>> ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) OrderJTable.getModel();
        dtm.setRowCount(0);
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof DistributorOrganization && org.getName().equals(organization.getName())) {
                for (WorkRequest request : distOrganization.getWorkQueue().getWorkRequestList()) {
                    if(request!=null && request instanceof DistributorRequest){
                        DistributorRequest request1 = (DistributorRequest) request;
                        Object[] row = new Object[8];
                        row[0] = request1.getRequestDate();
                        row[1] = request1.getSender();
                        row[2] = request1.getVaccine();
                        row[3] = request1.getVaccine().getName();
                        row[4] = request1.getStatus();
                        row[5] = request1.getResolveDate() == null ? request1.getRequestDate() : request1.getResolveDate();
                        row[6] = request1.getRequest();
                        
                        dtm.addRow(row);
              
                    }
                }
            }
        }
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
