/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.business.Business;
import business.network.Network;
import business.userAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import db4oUtil.DB4OUtil;

/**
 *
 * @author Rachita
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Business business;
    DB4OUtil connection = new DB4OUtil();

    public MainJFrame() {
        initComponents();

        business = connection.retrieveSystem();
//         populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        btnLogout = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPassword)
                    .addComponent(txtUsername)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(236, 236, 236)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setMaximumSize(new java.awt.Dimension(12000, 12000));
        userProcessContainer.setMinimumSize(new java.awt.Dimension(12000, 12000));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private void populateComboBox(){
//        cmbNetwork.removeAllItems();
//        for(Network network: business.getNetworkList()){
//            cmbNetwork.addItem(network);
//        }
//    }

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

  
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        userProcessContainer.removeAll();
        txtUsername.setText(null);
        jPassword.setText(null);
        txtUsername.setEnabled(true);
        jPassword.setEnabled(true);
        btnLogout.setEnabled(false);
        btnLogin.setEnabled(true);
        connection.storeSystem(business);

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        char[] passwordArrayChar = jPassword.getPassword();
       // username = "sysadmin";

        String password = String.valueOf(passwordArrayChar);
       // password = "sysadmin";

        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        UserAccount userAccount = null;

        if (business.getUserAccountDirectory().getUserValid(username, password)) {

            userAccount = business.getUserAccountDirectory().getUser(username, password);
            System.out.println("in business getUserDire: " + userAccount);

        } else if(userAccount==null) {
            for (Network countryNet : business.getNetworkList()) {
                // check country enterprise
                System.out.println("inside countrynet : " + countryNet);
                for (Enterprise CDCEnt : countryNet.getEnterpriseDirectory().getEnterpriseList()) {
                    System.out.println("inside cdc ent : ");
                    if (CDCEnt.getUserAccountDirectory().getUserValid(username, password)) {

                        userAccount = CDCEnt.getUserAccountDirectory().getUser(username, password);
                        inEnterprise = CDCEnt;
                        System.out.println("in cdc ent getuserAccount: " + userAccount);
                        System.out.println("in cdc org inEnterprise: " + CDCEnt);
                    } else if(userAccount==null) {


                                for (Network statenet : countryNet.getNetWorkList()) {
                                    System.out.println("inside statenet : " + statenet);

                                    for (Enterprise phdent : statenet.getEnterpriseDirectory().getEnterpriseList()) {
                                        System.out.println("inside phdend  : ");
                                        if (phdent.getUserAccountDirectory().getUserValid(username, password)) {

                                            userAccount = phdent.getUserAccountDirectory().getUser(username, password);

                                            System.out.println("in phd ent getuserAccount: " + userAccount);
                                  
                                            System.out.println("in cdc org inEnterprise: " + phdent);
                                            //System.out.println("in cdc org inOrg: " + inOrganization);
                                            inEnterprise = phdent;
                                             //inOrganization = orgcdc;
          
                                        } 
//                                        else if(userAccount==null) {
//                                            for (Organization orgphd : phdent.getOrganizationDirectory().getOrganizationList()) {
//                                                System.out.println("inside orgphd: ");
//                                                if (orgphd.getUserAccountDirectory().getUserValid(username, password)) {
//
//                                                    userAccount = orgphd.getUserAccountDirectory().getUser(username, password);
//                                                    System.out.println("in orgphd getuserAccount: " + userAccount);
//                                                    System.out.println("in cdc org inEnterprise: " + phdent);
//                                                    System.out.println("in cdc org inOrg: " + inOrganization);
//                                                    inEnterprise = phdent;
//                                                    inOrganization = orgphd;
//
//
//                                                }
                                                else if(userAccount==null) {

                                                    for (Network citynet : statenet.getNetWorkList()) {
                                                        System.out.println("inside citynet : " + citynet);

                                                        for (Enterprise provider : citynet.getEnterpriseDirectory().getEnterpriseList()) {
                                                            System.out.println("inside provider  : ");
                                                            if (provider.getUserAccountDirectory().getUserValid(username, password)) {

                                                                userAccount = provider.getUserAccountDirectory().getUser(username, password);

                                                                System.out.println("in provider getuserAccount: " + userAccount);
                                                                 System.out.println("in cdc org inEnterprise: " + provider);
                                                 
                                                                  inEnterprise = provider;
                                                                
                                                            } else if(userAccount==null) {

                                                                for (Organization orgprovider : provider.getOrganizationDirectory().getOrganizationList()) {
                                                                    System.out.println("inside orgprovider: ");
                                                                    if (orgprovider.getUserAccountDirectory().getUserValid(username, password)) {

                                                                        userAccount = orgprovider.getUserAccountDirectory().getUser(username, password);
                                                                        System.out.println("in orgprovider getuserAccount: " + userAccount);
                                                                        
                                                                        System.out.println("in cdc org inEnterprise: " + provider);
                                                                        System.out.println("in cdc org inOrg: " + orgprovider);
                                                                        inEnterprise = provider;
                                                                        inOrganization = orgprovider;

                                                                    } else{// if(userAccount==null) {

                                                                        userAccount = null;
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    //}
               // }

        for (Network countryNet : business.getNetworkList()) {
            for (Enterprise CDCEnt : countryNet.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization orgcdc : CDCEnt.getOrganizationDirectory().getOrganizationList()) {
                    System.out.println("inside org cdc: ");
                    if (orgcdc.getUserAccountDirectory().getUserValid(username, password)) {

                        userAccount = orgcdc.getUserAccountDirectory().getUser(username, password);
                        System.out.println("in cdc org getuserAccount: " + userAccount);
                        System.out.println("in cdc org inEnterprise: " + CDCEnt);
                        System.out.println("in cdc org inOrg: " + inOrganization);
                        inEnterprise = CDCEnt;
                        inOrganization = orgcdc;

                    }
                }
            }
        }
         if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid User Credentials");
            userProcessContainer.removeAll();
            txtUsername.setText(null);
            jPassword.setText(null);
            btnLogin.setEnabled(true);
//            cmbNetwork.setEnabled(true);
        } else {
            btnLogin.setEnabled(false);
            txtUsername.setEnabled(false);
            jPassword.setEnabled(false);
            btnLogout.setEnabled(true);
//            cmbNetwork.setEnabled(false);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            System.out.println("username" + userAccount.getUserName() + "password" + userAccount.getPassword());
            userProcessContainer.add("WorkArea", userAccount.getRole().CreateWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, business));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //MainJFrame m = new MainJFrame();
        //m.btnLoginActionPerformed(null);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
